x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  bitcoin-signing-server:
    build:
      context: ./bitcoin-signing-server
      dockerfile: Dockerfile
      args:
        - USER=btc-signing-server
        - DOCKER_REPO=${BTC_SIGNING_SERVER_DOCKER_REPO}
        - DOCKER_TAG=${BTC_SIGNING_SERVER_DOCKER_TAG}
    image: bitcoin-signing-server:local
    pull_policy: never
    restart: unless-stopped
    environment:
      - BITCOIND_HOST=${BITCOIND_HOST}
      - BITCOIND_USER=${BITCOIND_USER}
      - BITCOIND_PASS=${BITCOIND_PASS}
    entrypoint:
      - docker-entrypoint.sh
      - server
      - --btc-network=bitcoin
      - --identifier=${FROST_IDENTIFIER}
      - --address=0.0.0.0:8080
      - --db=/bitcoin-server/data/db
      - --min-signers=12
      - --max-signers=16
      - --toml=/bitcoin-server/config/config.toml
      - --fee-rate-diff-percentage=30
      - --bitcoind-url=${BITCOIND_HOST}
      - --bitcoind-user=${BITCOIND_USER}
      - --bitcoind-pass=${BITCOIND_PASS}
      - --btc-signing-server-jwt-secret=/bitcoin-server/config/jwt.hex
      - --fall-back-fee-rate-sat-per-vbyte=5
      - --metrics-port=7000
      - --federation-config-path=/bitcoin-server/config/chain.toml
      - --p2p-secret-key=/bitcoin-server/config/discovery-secret
      - --coordinator=0
    <<: *logging
    volumes:
      - ./config:/config:rw
      - signing-server-data:/bitcoin-server/data:rw

  reth:
    entrypoint:
      - docker-entrypoint.sh
      - reth
      - poa
      - --federation-config-path=/reth/config/chain.toml
      - --datadir=/reth/data
      - --http
      - --http.addr=0.0.0.0
      - --http.port=${EL_RPC_PORT:-8545}
      - --http.api=debug,eth,net,trace,txpool,web3,rpc
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=${EL_WS_PORT:-8546}
      - --ws.api=debug,eth,net,trace,txpool,web3,rpc
      - -vvv
      - --btc-signing-server-jwt-secret=/reth/config/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --btc-server=bitcoin-signing-server:8080
      - --bitcoind.url=${BITCOIND_HOST}
      - --bitcoind.username=${BITCOIND_USER}
      - --bitcoind.password=${BITCOIND_PASS}
      - --frost.min_signers=12
      - --frost.max_signers=16
      - --p2p-secret-key=/reth/config/discovery-secret
      - --port=${EL_P2P_PORT:-30303}
      - --btc-network=bitcoin
      - --metrics=0.0.0.0:9001
      - --federation-mode
      - --abci-port=26658
      - --ipcdisable
      - --abci-host=0.0.0.0
      - --cometbft-rpc-port=${CL_RPC_PORT:-26657}
      - --cometbft-rpc-host=cometbft
      - --sync.enable_state_sync
      - --sync.enable_historical_sync
      - --block-fee-recipient-address=${REWARDS_RECIPIENT}
      - --txpool.minimum-priority-fee=0
    depends_on:
      - bitcoin-signing-server

  import-cometbft-keys:
    profiles: ["tools"]
    build:
      context: ./cometbft
      dockerfile: Dockerfile
      args:
        - USER=cosmos
    image: cometbft:local
    pull_policy: never
    user: root
    volumes:
      - cometbft-data:/cometbft:rw
      - ./keys/cometbft:/data/config:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        echo "Importing validator key and state file from ./keys/cometbft into container"
        cp /data/config/node_key.json /cometbft/config/
        cp /data/config/priv_validator_key.json /cometbft/config/
        cp /data/config/priv_validator_state.json /cometbft/data/
        chown -R cosmos:cosmos /cometbft/config
        chown -R cosmos:cosmos /cometbft/data
        echo "Validator keys imported!"

  import-btc-key:
    profiles: ["tools"]
    build:
      context: ./bitcoin-signing-server
      dockerfile: Dockerfile
      args:
        - USER=btc-signing-server
        - DOCKER_REPO=${BTC_SIGNING_SERVER_DOCKER_REPO}
        - DOCKER_TAG=${BTC_SIGNING_SERVER_DOCKER_TAG}
    image: bitcoin-signing-server:local
    pull_policy: never
    user: root
    volumes:
      - ./keys/bitcoin-signing-server/keys:/keys:rw
      - signing-server-data:/bitcoin-server/data:rw
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        echo "Importing db file from ./keys/bitcoin-signing-server into container"
        mkdir -p /bitcoin-server/data/db
        cp /keys/db /bitcoin-server/data/db/db
        chown -R btc-signing-server:btc-signing-server /bitcoin-server/data/
        echo "BTC Signing Key Imported!"

volumes:
  signing-server-data:
